---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsmith-deployment
  namespace: tst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsmith
  template:
    metadata:
      labels:
        app: appsmith
    spec:
      nodeSelector:
        kubernetes.io/hostname: "timesheet-workernode-091f3ddf61a2" 
      containers:
        - name: appsmith-container
          image: appsmith/appsmith-ee  
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: appsmith-smtp-config


---
kind: Deployment
apiVersion: v1
kind: Service
metadata:
  name: appsmith-service
  namespace: tst
spec:
  selector:
    app: appsmith
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
