apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-01-28T12:59:57Z","generation":1,"labels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer","app.kubernetes.io/version":"ce-latest-ee-2.21.5","io.portainer.kubernetes.application.stack":"portainer"},"name":"portainer","namespace":"portainer","resourceVersion":"61835","uid":"651d3606-8dc7-4ce4-8349-a36de8d13457"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer"}},"spec":{"containers":[{"args":["--tunnel-port=30776"],"image":"portainer/portainer-ce:2.21.5","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":9443,"scheme":"HTTPS"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"portainer","ports":[{"containerPort":9000,"name":"http","protocol":"TCP"},{"containerPort":9443,"name":"https","protocol":"TCP"},{"containerPort":8000,"name":"tcp-edge","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":9443,"scheme":"HTTPS"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data","name":"data"}]}],"dnsPolicy":"ClusterFirst","nodeSelector":{"kubernetes.io/hostname":"worker-nodes-a5f6f06e240d"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"portainer-sa-clusteradmin","serviceAccountName":"portainer-sa-clusteradmin","terminationGracePeriodSeconds":30,"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"portainer"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2025-01-28T12:59:57Z","lastUpdateTime":"2025-01-28T12:59:57Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2025-01-28T13:09:58Z","lastUpdateTime":"2025-01-28T13:09:58Z","message":"ReplicaSet \"portainer-5486b6577f\" has timed out progressing.","reason":"ProgressDeadlineExceeded","status":"False","type":"Progressing"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-01-28T12:59:57Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: ce-latest-ee-2.21.5
    io.portainer.kubernetes.application.stack: portainer
  name: portainer
  namespace: portainer
  resourceVersion: "65543"
  uid: 651d3606-8dc7-4ce4-8349-a36de8d13457
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: portainer
      app.kubernetes.io/name: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: portainer
        app.kubernetes.io/name: portainer
    spec:
      containers:
      - args:
        - --tunnel-port=30776
        image: portainer/portainer-ce:2.21.5
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: portainer
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9443
          name: https
          protocol: TCP
        - containerPort: 8000
          name: tcp-edge
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: portainer-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: worker-nodes-a5f6f06e240d
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: portainer-sa-clusteradmin
      serviceAccountName: portainer-sa-clusteradmin
      terminationGracePeriodSeconds: 30
      volumes:
      - name: portainer-data
        hostPath:
          path: /portainer/data
          type: Directory
status:
  conditions:
  - lastTransitionTime: "2025-01-28T12:59:57Z"
    lastUpdateTime: "2025-01-28T12:59:57Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-01-28T13:33:12Z"
    lastUpdateTime: "2025-01-28T13:33:12Z"
    message: ReplicaSet "portainer-787d4bf44d" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
