apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-01-28T12:59:56Z","labels":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer","app.kubernetes.io/version":"ce-latest-ee-2.21.5","io.portainer.kubernetes.application.stack":"portainer"},"name":"portainer","namespace":"portainer","resourceVersion":"60190","uid":"6c70da9f-e2ed-4cdd-9e5b-790c51a4f139"},"spec":{"clusterIP":"10.105.65.149","clusterIPs":["10.105.65.149"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","nodePort":30777,"port":9000,"protocol":"TCP","targetPort":9000},{"name":"https","nodePort":30779,"port":9443,"protocol":"TCP","targetPort":9443},{"name":"edge","nodePort":30776,"port":30776,"protocol":"TCP","targetPort":30776}],"selector":{"app.kubernetes.io/instance":"portainer","app.kubernetes.io/name":"portainer"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2025-01-28T12:59:56Z"
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: ce-latest-ee-2.21.5
    io.portainer.kubernetes.application.stack: portainer
  name: portainer-service
  namespace: portainer
  resourceVersion: "61324"
  uid: 6c70da9f-e2ed-4cdd-9e5b-790c51a4f139
spec:
  clusterIP: 10.105.65.149
  clusterIPs:
  - 10.105.65.149
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: https
    port: 9443
    protocol: TCP
    targetPort: 9443
  - name: edge
    port: 30776
    protocol: TCP
    targetPort: 30776

  selector:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
